// src/pages/tools/generator.tsx
import { useCallback, useEffect, useState } from 'react';
import { signIn, useSession } from 'next-auth/react';
import { useRouter } from 'next/router';

type TaskComplexity = 'SIMPLE' | 'MEDIUM' | 'HIGH';
type TaskCategory = 'ARCHITECTURE' | 'MODEL' | 'SERVICE' | 'VIEW' | 'INFRA' | 'QA';

interface GeneratedTask {
  id: string;
  title: string;
  description: string;
  category: TaskCategory;
  complexity: TaskComplexity;
  priority: number;
  estimatedHours: number;
  hourlyRate: number;
  taskPrice: number;
}

interface ProjectEstimation {
  id?: string;
  projectTitle: string;
  projectDescription: string;
  ownerEmail: string;
  tasks: GeneratedTask[];
  totalHours: number;
  totalTasksPrice: number;
  platformFeePercent: number;
  platformFeeAmount: number;
  generatorServiceFee: number;
  grandTotalClientCost: number;
}

export default function GeneratorPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const API_BASE = process.env.NEXT_PUBLIC_BACKEND_URL || 'http://localhost:4000';

  const [projectTitle, setProjectTitle] = useState('');
  const [projectDescription, setProjectDescription] = useState('');
  const [ownerEmail, setOwnerEmail] = useState('');
  const [result, setResult] = useState<ProjectEstimation | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isPublishing, setIsPublishing] = useState(false);
  const [publishError, setPublishError] = useState<string | null>(null);

  const [checkingSubscription, setCheckingSubscription] = useState(false);
  const [showSubscriptionModal, setShowSubscriptionModal] = useState(false);
  const [hasActiveSubscription, setHasActiveSubscription] = useState<boolean | null>(null);
  const [stripeError, setStripeError] = useState<string | null>(null);
  const [checkoutLoading, setCheckoutLoading] = useState(false);
  const [checkoutError, setCheckoutError] = useState<string | null>(null);
  const [autoGenerateDone, setAutoGenerateDone] = useState(false);

  const effectiveOwnerEmail = ownerEmail || (session?.user?.email as string) || '';
  const checkoutStatus = typeof router.query.status === 'string' ? router.query.status : undefined;

  const isPaymentSuccess = checkoutStatus === 'success';
  const isPaymentCanceled = checkoutStatus === 'cancel';

  const formatPrice = (value: number) =>
    new Intl.NumberFormat('es-ES', { style: 'currency', currency: 'EUR' }).format(value);

  // --- Normalización de la respuesta del backend ---
  const normalizeProjectEstimation = useCallback(
    (raw: any): ProjectEstimation => {
      const num = (v: any, fallback = 0) =>
        typeof v === 'number' && !Number.isNaN(v) ? v : fallback;

      const tasks: GeneratedTask[] = Array.isArray(raw.tasks) ? raw.tasks : [];

      const totalHours = num(
        raw.totalHours,
        tasks.reduce((acc, t) => acc + num(t.estimatedHours, 0), 0)
      );

      const totalTasksPrice = num(
        raw.totalTasksPrice,
        tasks.reduce((acc, t) => acc + num(t.taskPrice, 0), 0)
      );

      const platformFeePercent = num(raw.platformFeePercent, 1);
      const generatorServiceFee = num(raw.generatorServiceFee, 0);

      const platformFeeAmount = num(
        raw.platformFeeAmount,
        (totalTasksPrice * platformFeePercent) / 100
      );

      const grandTotalClientCost = num(
        raw.grandTotalClientCost,
        totalTasksPrice + platformFeeAmount + generatorServiceFee
      );

      return {
        id: raw.id ?? raw.projectId,
        projectTitle: raw.projectTitle ?? projectTitle,
        projectDescription: raw.projectDescription ?? projectDescription,
        ownerEmail: raw.ownerEmail ?? effectiveOwnerEmail,
        tasks,
        totalHours,
        totalTasksPrice,
        platformFeePercent,
        platformFeeAmount,
        generatorServiceFee,
        grandTotalClientCost,
      };
    },
    [effectiveOwnerEmail, projectDescription, projectTitle]
  );

  // --- Restaurar proyecto pendiente desde localStorage ---
  useEffect(() => {
    if (typeof window === 'undefined') return;
    if (!effectiveOwnerEmail) return;

    try {
      const raw = window.localStorage.getItem('pendingProject');
      if (!raw) return;

      const parsed = JSON.parse(raw) as {
        ownerEmail?: string;
        projectTitle?: string;
        projectDescription?: string;
      };

      if (parsed.ownerEmail && parsed.ownerEmail === effectiveOwnerEmail) {
        if (!projectTitle && parsed.projectTitle) {
          setProjectTitle(parsed.projectTitle);
        }
        if (!projectDescription && parsed.projectDescription) {
          setProjectDescription(parsed.projectDescription);
        }
      }
    } catch (e) {
      console.error('[generator] Error parsing pendingProject from localStorage', e);
    }
  }, [effectiveOwnerEmail, projectDescription, projectTitle]);

  // --- Leer flag local de suscripción desde localStorage ---
  useEffect(() => {
    if (typeof window === 'undefined') return;
    if (!effectiveOwnerEmail) return;

    const key = `subscription:${effectiveOwnerEmail}`;
    const stored = window.localStorage.getItem(key);
    if (stored === 'active') {
      console.log(
        '[generator] Suscripción activa detectada en localStorage para',
        effectiveOwnerEmail
      );
      setHasActiveSubscription(true);
    }
  }, [effectiveOwnerEmail]);

  // --- Comprobación de suscripción contra el backend ---
  const checkSubscription = useCallback(
    async (email: string) => {
      try {
        setCheckingSubscription(true);

        const res = await fetch(
          `${API_BASE}/billing/me-subscription?email=${encodeURIComponent(email)}`
        );

        if (!res.ok) {
          console.error('[generator] Error HTTP comprobando suscripción', res.status);
          return;
        }

        const data = await res.json();
        console.log('[generator] subscription data from backend', data);

        if (data.hasActiveSubscription) {
          setHasActiveSubscription(true);
          if (typeof window !== 'undefined') {
            window.localStorage.setItem(`subscription:${email}`, 'active');
          }
        } else {
          setHasActiveSubscription((prev) => (prev === true ? true : false));
        }
      } catch (err) {
        console.error('[generator] Error checking subscription', err);
      } finally {
        setCheckingSubscription(false);
      }
    },
    [API_BASE]
  );

  useEffect(() => {
    const email = session?.user?.email;
    if (!email) return;
    checkSubscription(email);
  }, [session?.user?.email, checkSubscription]);

  // --- Llamada real al backend para generar tareas ---
  const actuallyGenerateTasks = useCallback(async () => {
    try {
      setIsLoading(true);
      setError(null);
      setResult(null);

      console.log('[generator] Generando tareas para', {
        projectTitle,
        projectDescription,
        ownerEmail: effectiveOwnerEmail,
      });

      const res = await fetch(`${API_BASE}/projects/generate-tasks`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          projectTitle,
          projectDescription,
          ownerEmail: effectiveOwnerEmail,
        }),
      });

      if (res.status === 402) {
        const data = await res.json().catch(() => ({}));
        console.error('[generator] 402 subscription_required', data);
        setStripeError(data.message || 'Necesitas una suscripción activa.');
        setShowSubscriptionModal(true);
        return;
      }

      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        console.error('[generator] Error HTTP generando tareas', res.status, data);
        throw new Error(data.error || 'No se pudo generar el troceado');
      }

      const raw = await res.json();
      console.log('[generator] Estimación recibida (raw)', raw);

      const data = normalizeProjectEstimation(raw);
      console.log('[generator] Estimación normalizada', data);

      setResult(data);

      if (typeof window !== 'undefined') {
        window.localStorage.removeItem('pendingProject');
        window.localStorage.setItem(
          'lastGeneratedProject',
          JSON.stringify({
            ownerEmail: data.ownerEmail,
            estimation: data,
          })
        );
      }
    } catch (err: any) {
      console.error('[generator] Error generating tasks', err);
      setError(err.message || 'Error al generar tareas.');
    } finally {
      setIsLoading(false);
    }
  }, [
    API_BASE,
    effectiveOwnerEmail,
    normalizeProjectEstimation,
    projectDescription,
    projectTitle,
  ]);

  // --- Publicar proyecto en la comunidad ---
  const handlePublishToCommunity = useCallback(async () => {
    if (!result?.id) {
      setPublishError('No se encontró el proyecto a publicar. Genera un desglose nuevamente.');
      return;
    }

    try {
      setIsPublishing(true);
      setPublishError(null);

      const res = await fetch(`${API_BASE}/community/projects/${result.id}/publish`, {
        method: 'POST',
      });

      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(
          data.error || 'No se pudo publicar el proyecto en la comunidad. Inténtalo de nuevo.'
        );
      }

      await res.json();
      router.push(`/community/projects/${result.id}`);
    } catch (err: any) {
      console.error('[generator] Error publicando en la comunidad', err);
      setPublishError(err.message || 'No se pudo publicar el proyecto en la comunidad.');
    } finally {
      setIsPublishing(false);
    }
  }, [API_BASE, result?.id, router]);

  // --- Handler principal de generación (gateado por suscripción) ---
  const handleGenerate = useCallback(async () => {
    setStripeError(null);
    setError(null);

    if (!projectTitle.trim() || !projectDescription.trim()) {
      setError('Introduce título y descripción del proyecto.');
      return;
    }

  const handleCreateCheckoutSession = async () => {
    if (!result?.id) {
      setCheckoutError('No se encontró el proyecto a pagar. Genera un desglose nuevamente.');
      return;
    }

    try {
      setCheckoutLoading(true);
      setCheckoutError(null);

      const res = await fetch(`${API_BASE}/payments/create-checkout-session`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ projectId: result.id, email: session.user?.email }),
      });

      if (!res.ok) {
        throw new Error('No se pudo iniciar el pago del proyecto.');
      }

      const data = await res.json();
      if (data?.url) {
        window.location.href = data.url;
      } else {
        throw new Error('Respuesta inesperada del servidor al crear la sesión de pago.');
      }
    } catch (err: any) {
      console.error('[checkout] Error creating checkout session', err);
      setCheckoutError(err.message || 'No se pudo crear la sesión de pago.');
    } finally {
      setCheckoutLoading(false);
    }
  };

    console.log(
      '[generator] handleGenerate -> hasActiveSubscription =',
      hasActiveSubscription
    );

    if (checkingSubscription) {
      console.log('[generator] Aún comprobando suscripción...');
      return;
    }

    // 🔐 Si NO está suscrito → guardar proyecto y mostrar modal
    if (!hasActiveSubscription) {
      if (typeof window !== 'undefined') {
        window.localStorage.setItem(
          'pendingProject',
          JSON.stringify({
            ownerEmail: effectiveOwnerEmail,
            projectTitle,
            projectDescription,
          })
        );
      }
      setShowSubscriptionModal(true);
      return;
    }

    // ✅ Suscripción OK → generar / regenerar
    await actuallyGenerateTasks();
  }, [
    actuallyGenerateTasks,
    checkingSubscription,
    effectiveOwnerEmail,
    hasActiveSubscription,
    projectDescription,
    projectTitle,
  ]);

  // --- Auto-generar al volver de Stripe con ?autoGenerate=1 ---
  useEffect(() => {
    if (!router.isReady) return;

    const { autoGenerate } = router.query;

    if (
      autoGenerate &&
      hasActiveSubscription === true &&
      !autoGenerateDone &&
      !checkingSubscription &&
      !isLoading &&
      projectTitle &&
      projectDescription
    ) {
      console.log('[generator] Auto-generando tras suscripción exitosa');
      handleGenerate();
      setAutoGenerateDone(true);
    }
  }, [
    router.isReady,
    router.query,
    hasActiveSubscription,
    autoGenerateDone,
    checkingSubscription,
    isLoading,
    projectTitle,
    projectDescription,
    handleGenerate,
  ]);

  // --- Estado de sesión ---
  if (status === 'loading') {
    return (
      <main className="flex min-h-screen items-center justify-center bg-slate-50 p-6">
        <p className="text-lg font-semibold text-slate-700">Cargando…</p>
      </main>
    );
  }

  if (!session) {
    return (
      <main className="flex min-h-screen items-center justify-center bg-slate-50 p-6">
        <div className="max-w-md rounded-2xl bg-white p-8 shadow-lg">
          <h1 className="mb-4 text-2xl font-bold text-slate-900">Acceso restringido</h1>
          <p className="mb-4 text-slate-600">
            Necesitas iniciar sesión con Google para usar el generador de tareas.
          </p>
          <button
            onClick={() => signIn('google')}
            className="w-full rounded-lg bg-blue-600 px-4 py-2 text-white hover:bg-blue-700"
          >
            Iniciar sesión con Google
          </button>
        </div>
      </main>
    );
  }

  // --- Render ---
  return (
    <main className="min-h-screen bg-slate-50 p-6">
      <div className="mx-auto max-w-5xl space-y-8 rounded-2xl bg-white p-8 shadow-lg">
        {isPaymentSuccess && (
          <div className="rounded-lg border border-green-200 bg-green-50 p-4 text-sm text-green-800">
            Pago completado. El desglose de tu proyecto ha sido confirmado.
          </div>
        )}

        {isPaymentCanceled && (
          <div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">
            Pago cancelado. Puedes intentarlo de nuevo cuando quieras.
          </div>
        )}

        <div className="flex flex-col gap-2">
          <p className="text-sm font-semibold uppercase tracking-wide text-blue-600">
            Herramienta
          </p>
          <h1 className="text-3xl font-bold text-slate-900">
            Generador de tareas y presupuesto
          </h1>
          <p className="text-slate-600">
            Divide tu proyecto en tareas con prioridad, capa técnica y precio estimado. La
            tarifa base de trabajo es de 30 €/h y la plataforma aplica un 1% de comisión
            sobre el importe total de las tareas. El acceso al generador se realiza mediante
            una suscripción de 30 €/mes.
          </p>
          <p className="text-sm text-slate-600">
            El cliente paga la suma de todas las tareas estimadas más ese 1% de comisión de
            plataforma. No se añade ningún fee adicional por el generador en cada
            presupuesto.
          </p>
        </div>

        <form
          onSubmit={(event) => {
            event.preventDefault();
            handleGenerate();
          }}
          className="grid gap-6 rounded-xl border border-slate-200 p-6"
        >
          <div className="flex flex-col gap-2">
            <label className="text-sm font-semibold text-slate-800" htmlFor="title">
              Título del proyecto
            </label>
            <input
              id="title"
              name="title"
              value={projectTitle}
              onChange={(e) => setProjectTitle(e.target.value)}
              required
              className="w-full rounded-lg border border-slate-200 px-4 py-2 focus:border-blue-500 focus:outline-none"
              placeholder="Ej. Automatización de correos electrónicos"
            />
          </div>

          <div className="flex flex-col gap-2">
            <label
              className="text-sm font-semibold text-slate-800"
              htmlFor="description"
            >
              Descripción del proyecto
            </label>
            <textarea
              id="description"
              name="description"
              value={projectDescription}
              onChange={(e) => setProjectDescription(e.target.value)}
              required
              rows={4}
              className="w-full rounded-lg border border-slate-200 px-4 py-2 focus:border-blue-500 focus:outline-none"
              placeholder="Describe las necesidades, el stack o los objetivos principales"
            />
          </div>

          <div className="flex flex-col gap-2">
            <label
              className="text-sm font-semibold text-slate-800"
              htmlFor="ownerEmail"
            >
              Email del propietario
            </label>
            <input
              id="ownerEmail"
              name="ownerEmail"
              type="email"
              value={ownerEmail || session.user?.email || ''}
              onChange={(e) => setOwnerEmail(e.target.value)}
              required
              disabled={Boolean(session.user?.email && !ownerEmail)}
              className="w-full rounded-lg border border-slate-200 px-4 py-2 text-slate-700 focus:border-blue-500 focus:outline-none disabled:cursor-not-allowed disabled:bg-slate-50"
              placeholder="tu@email.com"
            />
            <p className="text-xs text-slate-500">
              Usaremos este email para asociar el proyecto generado.
            </p>
          </div>

          <div className="flex flex-col gap-4 rounded-lg bg-slate-50 p-4 text-sm text-slate-700">
            <p>
              Este servicio está disponible mediante una suscripción de{' '}
              <strong>30 €/mes</strong> para convertir tu idea en un plan detallado de
              trabajo.
            </p>
            <p>
              La tarifa técnica base es de <strong>30 €/h</strong> y la plataforma
              aplicará un <strong>1%</strong> de comisión sobre el presupuesto de tareas
              generado.
            </p>
          </div>

          <button
            type="submit"
            className="w-full rounded-lg bg-blue-600 px-4 py-2 text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:bg-blue-300"
            disabled={isLoading}
          >
            {isLoading
              ? 'Generando tareas…'
              : result
              ? 'Regenerar tareas'
              : 'Generar tareas'}
          </button>

          {(error || stripeError) && (
            <p className="text-sm text-red-600">{error || stripeError}</p>
          )}
        </form>

        {result && (
          <div className="space-y-4 rounded-xl border border-slate-200 p-6">
            <div className="flex flex-col gap-1">
              <p className="text-sm font-semibold uppercase tracking-wide text-blue-600">
                Resultado
              </p>
              <h2 className="text-2xl font-bold text-slate-900">
                {result.projectTitle}
              </h2>
              <p className="text-slate-700">{result.projectDescription}</p>
              <p className="text-sm text-slate-600">
                La plataforma actúa como intermediaria entre el cliente y los
                programadores. El presupuesto mostrado incluye la suma de todas las tareas
                más un 1% de comisión de plataforma.
              </p>
            </div>

            <div className="overflow-x-auto">
              {result.tasks && result.tasks.length > 0 && (
                <table className="min-w-full divide-y divide-slate-200 text-left text-sm">
                  <thead className="bg-slate-50">
                    <tr>
                      <th className="px-4 py-2 font-semibold text-slate-700">Título</th>
                      <th className="px-4 py-2 font-semibold text-slate-700">
                        Descripción
                      </th>
                      <th className="px-4 py-2 font-semibold text-slate-700">
                        Categoría
                      </th>
                      <th className="px-4 py-2 font-semibold text-slate-700">
                        Complejidad
                      </th>
                      <th className="px-4 py-2 font-semibold text-slate-700">
                        Prioridad
                      </th>
                      <th className="px-4 py-2 font-semibold text-slate-700">Horas</th>
                      <th className="px-4 py-2 font-semibold text-slate-700">Tarifa</th>
                      <th className="px-4 py-2 font-semibold text-slate-700">Precio</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {result.tasks.map((task) => (
                      <tr key={task.id} className="hover:bg-slate-50">
                        <td className="px-4 py-2 font-semibold text-slate-900">
                          {task.title}
                        </td>
                        <td className="px-4 py-2 text-slate-700">
                          {task.description}
                        </td>
                        <td className="px-4 py-2 text-slate-700">{task.category}</td>
                        <td className="px-4 py-2 text-slate-700">
                          {task.complexity}
                        </td>
                        <td className="px-4 py-2 text-slate-700">{task.priority}</td>
                        <td className="px-4 py-2 text-slate-700">
                          {task.estimatedHours}
                        </td>
                        <td className="px-4 py-2 text-slate-700">
                          {task.hourlyRate.toFixed(2)} € / h
                        </td>
                        <td className="px-4 py-2 text-slate-900">
                          {formatPrice(task.taskPrice)}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>

            <div className="mt-6 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-3">
              <div>
                Horas totales estimadas:{' '}
                <strong>{result.totalHours}</strong>
              </div>
              <div>
                Presupuesto tareas:{' '}
                <strong>{formatPrice(result.totalTasksPrice)}</strong>
              </div>
              <div>
                Comisión plataforma ({result.platformFeePercent}%):{' '}
                <strong>{formatPrice(result.platformFeeAmount)}</strong>
              </div>
              <div className="sm:col-span-2 lg:col-span-3">
                Coste total estimado para el cliente:{' '}
                <strong>{formatPrice(result.grandTotalClientCost)}</strong>
              </div>
            </div>

            <div className="space-y-3">
              <button
                onClick={handleCreateCheckoutSession}
                disabled={checkoutLoading}
                className="w-full rounded-lg bg-blue-600 px-4 py-2 text-white hover:bg-blue-700 disabled:opacity-50"
              >
                {checkoutLoading ? 'Creando sesión de pago...' : 'Confirmar este desglose y pagar 30 €'}
              </button>
              {checkoutError && <p className="text-sm text-red-600">{checkoutError}</p>}
            </div>

            <div className="space-y-2">
              <button
                onClick={handlePublishToCommunity}
                disabled={isPublishing}
                className="mt-4 w-full rounded-lg border border-primary-500 px-4 py-2 text-sm font-semibold text-primary-700 hover:bg-primary-50 disabled:opacity-50"
              >
                {isPublishing ? 'Publicando...' : 'Publicar este proyecto en la comunidad'}
              </button>
              {publishError && <p className="text-sm text-red-600">{publishError}</p>}
            </div>
          </div>
        )}

        <SubscriptionModal
          open={showSubscriptionModal}
          onClose={() => setShowSubscriptionModal(false)}
          email={effectiveOwnerEmail}
          projectTitle={projectTitle}
          projectDescription={projectDescription}
        />
      </div>
    </main>
  );
}

function SubscriptionModal({
  open,
  onClose,
  email,
  projectTitle,
  projectDescription,
}: {
  open: boolean;
  onClose: () => void;
  email: string;
  projectTitle: string;
  projectDescription: string;
}) {
  const API_BASE = process.env.NEXT_PUBLIC_BACKEND_URL || 'http://localhost:4000';
  const [isRedirecting, setIsRedirecting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  if (!open) return null;

  const handleSubscribe = async () => {
    try {
      setIsRedirecting(true);
      setError(null);

      if (typeof window !== 'undefined') {
        window.localStorage.setItem(
          'pendingProject',
          JSON.stringify({
            ownerEmail: email,
            projectTitle,
            projectDescription,
          })
        );
      }

      const res = await fetch(`${API_BASE}/billing/create-subscription-session`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email }),
      });

      if (!res.ok) throw new Error('No se pudo iniciar la suscripción');

      const data = await res.json();
      window.location.href = data.url;
    } catch (err) {
      console.error('[subscription] Error creating session', err);
      setError('No se pudo iniciar la suscripción. Inténtalo de nuevo.');
      setIsRedirecting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
      <div className="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl">
        <h2 className="mb-2 text-xl font-semibold text-slate-900">
          Suscríbete para usar el generador
        </h2>
        <p className="mb-4 text-sm text-slate-600">
          El generador de tareas y presupuesto está disponible mediante una suscripción de{' '}
          <strong>30 €/mes</strong>. La plataforma conecta clientes y programadores y
          convierte tu idea en un plan detallado de trabajo.
        </p>
        {error && <p className="mb-3 text-sm text-red-600">{error}</p>}
        <div className="flex items-center justify-end gap-3">
          <button onClick={onClose} className="text-sm text-slate-500 hover:text-slate-700">
            Cancelar
          </button>
          <button onClick={handleSubscribe} disabled={isRedirecting} className="btn-primary">
            {isRedirecting ? 'Redirigiendo a Stripe…' : 'Suscribirme por 30 €/mes'}
          </button>
        </div>
      </div>
    </div>
  );
}
